apiVersion: apps/v1
kind: Deployment
metadata:
 name: icx-blog
 namespace: production
 labels:
   app: icx-blog
spec:
 replicas: 1
 selector:
   matchLabels:
     app: icx-blog
 template:
   metadata:
     labels:
       app: icx-blog
   spec:
     containers:
       - name: icx-api
         image: asia-southeast2-docker.pkg.dev/landx-id/icx-ar/icx-landing-page:latest
         imagePullPolicy: Always
         envFrom:
            - secretRef:
                name: icx-landing-page-secret
         ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: icx-blog-service
  namespace: production
  labels:
    app: icx-blog
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: icx-blog
