apiVersion: apps/v1
kind: Deployment
metadata:
 name: icx-landing-page
 namespace: production
 labels:
   app: icx-landing-page
spec:
 replicas: 1
 selector:
   matchLabels:
     app: icx-landing-page
 template:
   metadata:
     labels:
       app: icx-landing-page
   spec:
     containers:
       - name: icx-landing-page
         image: asia-southeast2-docker.pkg.dev/landx-id/icx-ar/icx-landing-page:latest
         imagePullPolicy: Always
         volumeMounts:
            - name: tz
              mountPath: /etc/localtime
              subPath: Jakarta
     volumes:
       - name: tz
         configMap:
            name: tz
---
apiVersion: v1
kind: Service
metadata:
  name: icx-landing-page-service
  namespace: production
  labels:
    app: icx-landing-page
spec:
  ports:
    - port: 443
      targetPort: 80
  selector:
    app: icx-landing-page

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icx-landing-page-ingress
  namespace: production
  labels:
    app: icx-landing-page
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
status:
  loadBalancer:
    ingress:
      - ip: 34.101.225.199
spec:
  rules:
    - host: icx.id
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service: 
                name: icx-landing-page-service
                port:
                  number: 80